name = "handy-tools"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

# 静态资源处理
[[routes]]
pattern = "/*"
zone_name = "your-subdomain.workers.dev"